import { YoutubeTranscript } from "youtube-transcript";
import { getRapidApiClient } from "../../lib/rapidapi";

export class YouTubeService {
  /**
   * Extracts the video ID from various YouTube URL formats.
   */
  extractVideoId(url: string): string | null {
    const regex = /(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/; 
    const match = url.match(regex);
    return match ? match[1] : null;
  }

  /**
   * Fetches the transcript using a Multi-Tiered Strategy.
   * 1. RapidAPI (Reliable, Requires Key)
   * 2. Piped API (Free, Public)
   * 3. Local Library (Last Resort)
   */
  async getTranscript(videoId: string): Promise<{ title: string; text: string } | null> {
    
    // --- Strategy 1: RapidAPI ---
    try {
        const rapid = getRapidApiClient();
        const text = await rapid.fetchTranscript(videoId);
        
        // RapidAPI transcript endpoint usually just returns text/segments.
        // We need to fetch the title separately via OEmbed.
        let title = `YouTube Video (${videoId})`;
        try {
            const oembedRes = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`);
            if (oembedRes.ok) {
                const data = await oembedRes.json() as any;
                title = data.title;
            }
        } catch {} // Ignore errors here

        console.log(`[YouTubeService] Success via RapidAPI`);
        return { title, text };
    } catch (e) {
        console.warn("[YouTubeService] RapidAPI failed (or not configured):", e);
    }

    // --- Strategy 2: Piped API ---
    const pipedInstances = [
      "https://pipedapi.kavin.rocks",
      "https://api.piped.nemb.one",
      "https://pipedapi.adminforge.de",
      "https://api.piped.privacy.com.de",
      "https://pipedapi.drg.li"
    ];

    for (const instance of pipedInstances) {
      try {
        console.log(`[YouTubeService] Trying Piped instance: ${instance}`);
        const res = await fetch(`${instance}/streams/${videoId}`);
        if (!res.ok) continue;
        
        const data = await res.json() as any;
        const title = data.title || `YouTube Video (${videoId})`;
        const description = data.description || "";
        const subtitles = data.subtitles || [];

        const engSub = subtitles.find((s: any) => s.code === 'en' && !s.autoGenerated) 
                    || subtitles.find((s: any) => s.code === 'en')
                    || subtitles[0];

        if (engSub) {
          const subRes = await fetch(engSub.url);
          if (subRes.ok) {
            const vttText = await subRes.text();
            const cleanText = this.parseVTT(vttText);
            console.log(`[YouTubeService] Success via Piped (${instance})`);
            return { title, text: cleanText };
          }
        }

        // Fallback to Description
        if (description) {
             console.log(`[YouTubeService] Success via Piped (Description Fallback)`);
             return { title, text: description };
        }
      } catch (e) {
        console.warn(`[YouTubeService] Piped instance ${instance} failed:`, e);
      }
    }

    // --- Strategy 3: Local Library ---
    try {
      console.log(`[YouTubeService] Trying Local Library...`);
      const transcriptItems = await YoutubeTranscript.fetchTranscript(videoId);
      const fullText = transcriptItems.map((item) => item.text).join(" ").replace(/\s+/g, " ").trim();
      
      let title = `YouTube Video (${videoId})`;
      try {
        const oembedRes = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`);
        if (oembedRes.ok) {
          const data = await oembedRes.json() as any;
          title = data.title;
        }
      } catch {} // Ignore errors here

      console.log(`[YouTubeService] Success via Local Library`);
      return { title, text: fullText };
    } catch (e) {
      console.warn(`[YouTubeService] Local Library failed:`, e);
    }

    // --- Strategy 4: OEmbed (Title Only) ---
    try {
        const oembedRes = await fetch(`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`);
        if (oembedRes.ok) {
          const data = await oembedRes.json() as any;
          console.log(`[YouTubeService] Success via OEmbed (Title Only)`);
          return { title: data.title, text: "" };
        }
    } catch {} // Ignore errors here

    return null;
  }

  private parseVTT(vtt: string): string {
    const lines = vtt.split('\n');
    let text = "";
    
    for (const line of lines) {
      const l = line.trim();
      if (!l || l.startsWith('WEBVTT') || l.includes('-->') || /^\d+$/.test(l)) continue;
      
      const cleanLine = l.replace(/<[^>]*>/g, "");
      text += cleanLine + " ";
    }
    
    return text.replace(/\s+/g, " ").trim();
  }
}

export const getYouTubeService = () => new YouTubeService();
